name: Rob√¥ Twilio Enfermaria

on:
  schedule:
    - cron: '*/5 * * * *' # Roda a cada 5 minutos
  workflow_dispatch:

jobs:
  run-twilio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install supabase twilio pytz
      - name: Rodar Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
        run: python automacao_medicamentos.py
